### ISSUE TITLE
Origin Crashs during a game download.

### ISSUE THREAD

**Issue by Alexander88207** [Tk-Glitch/PKGBUILDS#135]
Hi,

Origin crash's for me during a game download with wine-tkg 4.1 or higher.

I report this here because with the normal wine versions, that doesn't happen.

also doomicle from [here](https://lutris.net/games/origin/) have the same problem.

**Comment by Tk-Glitch** [comment]
Hi!
While wine-staging 4.1 had a known issue that was fixed in 4.2 (and also required a fresh prefix), I think the main problem here is related to the Lutris installer. Installing native vcrun2017 on 4.2 and up has broken Origin in some ways for me, up to breaking most (all?) Battlefield games.

If you cannot reproduce the issue with wine-staging 4.1+, please provide logs. Thanks !

**Comment by openglfreak** [comment]
You could also try with a newer vcrun2017 version: https://github.com/Winetricks/winetricks/pull/1191

**Comment by BrianAllred** [comment]
I can confirm this issue using wine-tkg-staging-git built today (so 4.5.something) and the latest VC++ 2017 redists (x86 and x64). wine-staging from the repos doesn't have this problem. Didn't even need a fresh prefix, just installed wine-staging over wine-tkg and re-ran Origin.

@Tk-Glitch What logs do you need?

**Comment by Tk-Glitch** [comment]
Installing vc redists on 4.2+ will frog your prefixes to begin with, but I guess disabling esync would be something to try before anything else.

**Comment by BrianAllred** [comment]
Disabling esync didn't seem to help. It *may* have taken longer to crash, but I don't know if time matters, and it still crashed in the end.

**Comment by Tk-Glitch** [comment]
Took some time to play with this one today. Could reproduce kinda consistently with all defaults. Couldn't reproduce with esync and staging shared mem disabled. It might be the shared mem.
You can disable it by exporting `STAGING_SHARED_MEMORY=0`.

**Comment by Sporif** [comment]
`STAGING_SHARED_MEMORY=0` fixes the crash but now upon installation I get  "An unexpected error has occurred. Please try again in a few moments. Error: 327682:11". Anyone know how to solve that? Happens with both wine-staging and tkg, vcrun2017 or not.

**Comment by Tk-Glitch** [comment]
Yeah this is a wine regression and has nothing to do with wine-tkg. No known workaround yet except using and older wine version. So at least we know Origin doesn't like STAGING_SHARED_MEMORY and that's a nice find.

**Comment by Alexander88207** [comment]
ahh nice now it works again thanks @Tk-Glitch for frogging out that :frog: .
