### ISSUE TITLE
[proton-tkg] -- proton branch selection feature request

### ISSUE THREAD

**Issue by skeevy420** [Tk-Glitch/PKGBUILDS#261]
I'm currently having major issues with a combination of Hitman 2, my PS4 controller & Proton 4.11 straight from Valve which, unfortunately, means that I'm also having issues with the current TKG builds.  

The same setups work just fine with Kingdom Come Deliverance so it's clearly something with Hitman 2.

Currently my method to work around that is to just stick with older builds and to keep two copies of everything provided here, master and right before the proton 4.11 commits.  If we had the option to pick a branch from the config it would simplify things a lot for me and possibly help out others as well.

Some of the problems I've been having with 4.11 + Hitman 2 + PS4 Controller
> Forced on causes my system to "force lock up".
> 
> Forced off make my PS4 controller do nothing in game. Ditto with the per game profile option.
> 
> Enabling PS4 controller support in Steam BPM while the game is running and then setting it to force off (a common fix for some Proton games) leaves the PS4 controller in desktop mode.
> 
> SC Controller in 360 Emulation mode causes my system to lock up.
> 
> Revert back to Proton 4.2 or any TKG build from before the 4.11 commits and it works just 
fine with any controller combination.
> 
> It's also the only controller connected to my system and is picked up as js0. 

Due to using mesa-git with ACO, fsync, llvm-git, etc, there is a lot that could the cause, but I'm not sure if those are actually the cause since it all works with other games and with Hitman 2 using older versions.  Once I validate my files for Hitman 2, I'll be able to test if it's related to dxvk-ags.  It's had a few updates lately and if a new one updated the amd_ags lib that could be a cause.

This is the downside of when you have so much custom stuff added. There's a lot to rule out before making a proper bug report on something.

**Comment by Tk-Glitch** [comment]
What happens if you disable proton gamepad additions from config? Does it help?

**Comment by skeevy420** [comment]
I haven't tried that yet.  Just my usual setup and stock Valve.

**Comment by Tk-Glitch** [comment]
The raw input fix doesn't affect gamepads at all

**Comment by skeevy420** [comment]
Rebuilt without gamepad additions and raw input fix and, in game Hitman 2, the only thing that works on the controller is the touchpad as mouse.  

That same build works fine with Kingdom Come.

**Comment by Tk-Glitch** [comment]
Ok so either a regression in the proton steamclient lib or Hitman 2 requires the proton gamepad additions and `dinput: Use the "PIDVID" GUID for the device product GUID` commit broke stuff.
You're not using xboxdrv or similar, right?

**Comment by skeevy420** [comment]
No, just the kernel driver and anything that's provided from here; except for one test with SC Controller in Xbox emulation mode last night that resulted in a system freeze.

For some reason, not matter what I do now it keeps using the desktop configuration and not switching over to a game mode.

**Comment by Tk-Glitch** [comment]
You can switch the branch from 4.11 to 4.2 in the proton-tkg script for a try. If that fixes your issue I'll add it to cfg options.

**Comment by skeevy420** [comment]
Ok, so I cloned the project to start fresh with no changes, only changed the branch line in the script and the custom name line, and it didn't work.  Not that surprising since changing the branch to 4.11 before you pushed the relevant 4.11 changes didn't work.  Yes, I tried that.

Wine finished with a Gandolf error and not sure on the Proton one other than it can't find a file.

[end_of_proton.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3458841/end_of_proton.log)
[end_of_wine.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3458842/end_of_wine.log)

**Comment by Tk-Glitch** [comment]
I have pushed https://github.com/Tk-Glitch/PKGBUILDS/commit/43e21688f6735d4b536ccd1ae94f7eb95f7e9bee (resolving that issue) with the additional changes needed for a successful compilation. Please test whether switching to the `proton_4.2` branch fixes your gamepad issue :frog:

**Comment by skeevy420** [comment]
So far I've tried two different builds with it set to use the 4.2 branch with Hitman 2, with and without proton_mf_hacks because it's new, and both behave like 4.11.  Controller is either not working or stays in desktop mode if Steam has PS4 controller support enabled.

**Comment by skeevy420** [comment]
I was about to swap those exports around and try that when I realized that proton_template/conf/proton is also going to need some if statements as well as CURRENT_PREFIX_VERSION="4.11-1" probably shouldn't be hardcoded to 4.11 either.  

Unlike sh and variants, I don't know python very well so I'd really be bumbling around trying to do that even though the 4.11 bring up commit pretty much lays it out...

**Comment by skeevy420** [comment]
For an update, the latest 4.11 builds still don't work with my PS4 controller & Hitman 2 and I've tried both mesa-git & mesa-aco as well as both llvm 9 and llvm 10 all with the same results.  I was hoping that Steam Common Runtime update would have helped.  

llvm 10 started having build errors when building mesa-aco so I reverted llvm-git to tag=release/9.x and my builds started finishing again.  Just an FYI mention.

I also tried unplugging my keyboard due to some of the recent issues, here and Proton, and that didn't help.

Did a diff of the log from 4.11 and 4.2 and the only thing that really stood out was `C:\\windows\\winsxs\\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef\\comctl32.dll` and that quite a few builtins are now native.

At least I've reverted enough to rule it a strictly Proton 4.11 issue so I can actually open a bug report there.
